import { DummyProduct, FakeProduct } from "./definitions";

export const products: DummyProduct[] = [
  {
    id: 1,
    title: "ریمل اسنس شاهزاده خانگ مژه",
    description:
      "ریمل اسنس شاهزاده خانگ مژه یک ریمل محبوب است که به خاطر اثرات حجیم کننده و بلند کننده شناخته می شود. با این فرمول پایدار و بدون قساوت به مژه های دراماتیک دست پیدا کنید.",
    category: "زیبایی",
    price: 9.99,
    discountPercentage: 10.48,
    rating: 2.56,
    stock: 99,
    tags: ["زیبایی", "ریمل"],
    brand: "Essence",
    sku: "BEA-ESS-ESS-001",
    weight: 4,
    dimensions: {
      width: 15.14,
      height: 13.08,
      depth: 22.99,
    },
    warrantyInformation: "گارانتی 1 هفته ای",
    shippingInformation: "ارسال در 3-5 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 3,
        comment: "توصیه نمی کنم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eleanor Collins",
        reviewerEmail: "eleanor.collins@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "خیلی راضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lucas Gordon",
        reviewerEmail: "lucas.gordon@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eleanor Collins",
        reviewerEmail: "eleanor.collins@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 48,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "5784719087687",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
  },
  {
    id: 2,
    title: "پالت سایه چشم با آینه",
    description:
      "پالت سایه چشم با آینه طیف متنوعی از سایه های چشم برای ایجاد لوک های چشم خیره کننده ارائه می دهد. با داشتن آینه داخلی، برای آرایش در حین حرکت مناسب است.",
    category: "زیبایی",
    price: 19.99,
    discountPercentage: 18.19,
    rating: 2.86,
    stock: 34,
    tags: ["زیبایی", "سایه چشم"],
    brand: "Glamour Beauty",
    sku: "BEA-GLA-EYE-002",
    weight: 9,
    dimensions: {
      width: 9.26,
      height: 22.47,
      depth: 27.67,
    },
    warrantyInformation: "گارانتی 1 ساله",
    shippingInformation: "ارسال در 2 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Savannah Gomez",
        reviewerEmail: "savannah.gomez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "محصول فوق العاده!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Christian Perez",
        reviewerEmail: "christian.perez@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 20,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9170275171413",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
  },
  {
    id: 3,
    title: "قوطی پودر",
    description:
      "قوطی پودر یک پودر ثابت کننده آسیاب شده است که برای ثابت کردن آرایش و کنترل درخشندگی طراحی شده است. با فرمول سبک و شفاف، پایه ای صاف و مات ارائه می دهد.",
    category: "زیبایی",
    price: 14.99,
    discountPercentage: 9.84,
    rating: 4.64,
    stock: 89,
    tags: ["زیبایی", "پودر صورت"],
    brand: "Velvet Touch",
    sku: "BEA-VEL-POW-003",
    weight: 8,
    dimensions: {
      width: 29.27,
      height: 27.93,
      depth: 20.59,
    },
    warrantyInformation: "گارانتی 3 ماهه",
    shippingInformation: "ارسال در 1-2 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "دوباره می خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Alexander Jones",
        reviewerEmail: "alexander.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elijah Cruz",
        reviewerEmail: "elijah.cruz@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "خیلی ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Avery Perez",
        reviewerEmail: "avery.perez@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 22,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "8418883906837",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
  },
  {
    id: 4,
    title: "رژلب قرمز",
    description:
      "رژلب قرمز یک انتخاب کلاسیک و جسورانه برای اضافه کردن رنگ به لب های شما است. با فرمول کرمی و پررنگ، پایه ای درخشان و ماندگار ارائه می دهد.",
    category: "زیبایی",
    price: 12.99,
    discountPercentage: 12.16,
    rating: 4.36,
    stock: 91,
    tags: ["زیبایی", "رژلب"],
    brand: "Chic Cosmetics",
    sku: "BEA-CHI-LIP-004",
    weight: 1,
    dimensions: {
      width: 18.11,
      height: 28.38,
      depth: 22.17,
    },
    warrantyInformation: "گارانتی 3 ساله",
    shippingInformation: "ارسال در 1 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "دوباره می خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 40,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9467746727219",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
  },
  {
    id: 5,
    title: "لاک ناخن قرمز",
    description:
      "لاک ناخن قرمز با رنگ قرمز غنی و براق برای ناخن های پرانرژی و آراسته ارائه می شود. با فرمول خشک شونده سریع، پایه ای با کیفیت سالن در خانه ارائه می دهد.",
    category: "زیبایی",
    price: 8.99,
    discountPercentage: 11.44,
    rating: 4.32,
    stock: 79,
    tags: ["زیبایی", "لاک ناخن"],
    brand: "Nail Couture",
    sku: "BEA-NAI-NAI-005",
    weight: 8,
    dimensions: {
      width: 21.63,
      height: 16.48,
      depth: 29.84,
    },
    warrantyInformation: "گارانتی 1 ماهه",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 2,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Benjamin Wilson",
        reviewerEmail: "benjamin.wilson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "خیلی از خریدم ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 22,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "4063010628104",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
  },
  {
    id: 6,
    title: "کالوین کلین سی کی وان",
    description:
      "سی کی وان توسط کالوین کلین یک عطر کلاسیک یونیسکس است که به خاطر رایحه تازه و تمیزش شناخته می شود. این یک عطر همه کاره مناسب برای استفاده روزانه است.",
    category: "عطرها",
    price: 49.99,
    discountPercentage: 1.89,
    rating: 4.37,
    stock: 29,
    tags: ["عطرها", "عطر"],
    brand: "Calvin Klein",
    sku: "FRA-CAL-CAL-006",
    weight: 7,
    dimensions: {
      width: 29.36,
      height: 27.76,
      depth: 20.72,
    },
    warrantyInformation: "گارانتی 1 هفته ای",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 2,
        comment: "خیلی ناامید شدم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Layla Young",
        reviewerEmail: "layla.young@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "ارسال سریع!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "مطابق توصیف نبود!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jacob Cooper",
        reviewerEmail: "jacob.cooper@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 90 روزه",
    minimumOrderQuantity: 9,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "2451534060749",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
  },
  {
    id: 7,
    title: "شنل کوکو نوآر او دو",
    description:
      "کوکو نوآر توسط شنل یک عطر ظریف و مرموز است که دارای نت های گریپ فروت، رز و صندل است. برای مناسبت های شبانه عالی است.",
    category: "عطرها",
    price: 129.99,
    discountPercentage: 16.51,
    rating: 4.26,
    stock: 58,
    tags: ["عطرها", "عطر"],
    brand: "Chanel",
    sku: "FRA-CHA-CHA-007",
    weight: 7,
    dimensions: {
      width: 24.5,
      height: 25.7,
      depth: 25.98,
    },
    warrantyInformation: "گارانتی 3 ساله",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "محصول فوق العاده!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Leah Henderson",
        reviewerEmail: "leah.henderson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "خیلی از خریدم راضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "4091737746820",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
  },
  {
    id: 8,
    title: "دیور ژادور",
    description:
      "ژادور توسط دیور یک عطر لوکس و گلدار است که به خاطر ترکیب ایلانگ-ایلانگ، رز و یاسمین شناخته می شود. این عطر زنانه بودن و پیچیدگی را تجسم می بخشد.",
    category: "عطرها",
    price: 89.99,
    discountPercentage: 14.72,
    rating: 3.8,
    stock: 98,
    tags: ["عطرها", "عطر"],
    brand: "Dior",
    sku: "FRA-DIO-DIO-008",
    weight: 4,
    dimensions: {
      width: 27.67,
      height: 28.28,
      depth: 11.83,
    },
    warrantyInformation: "گارانتی 1 هفته ای",
    shippingInformation: "ارسال در 2 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "ارزش عالی برای پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "ارزش عالی برای پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Emma Miller",
        reviewerEmail: "emma.miller@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "1445086097250",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
  },
  {
    id: 9,
    title: "دولچه شاین او دو",
    description:
      "دولچه شاین توسط دولچه اند گابانا یک عطر پرانرژی و میوه ای است که دارای نت های انبه، یاسمین و چوب های بلوند است. این یک رایحه شاد و جوانانه است.",
    category: "عطرها",
    price: 69.99,
    discountPercentage: 0.62,
    rating: 3.96,
    stock: 4,
    tags: ["عطرها", "عطر"],
    brand: "Dolce & Gabbana",
    sku: "FRA-DOL-DOL-009",
    weight: 6,
    dimensions: {
      width: 27.28,
      height: 29.88,
      depth: 18.3,
    },
    warrantyInformation: "گارانتی 3 ساله",
    shippingInformation: "ارسال در 1 ماه",
    availabilityStatus: "موجودی کم",
    reviews: [
      {
        rating: 4,
        comment: "دوباره می خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "توصیه می شود!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "خیلی از خریدم راضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aurora Lawson",
        reviewerEmail: "aurora.lawson@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "3023868210708",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
  },
  {
    id: 10,
    title: "گوچی بلوم او دو",
    description:
      "گوچی بلوم توسط گوچی یک عطر گلدار و جذاب است که دارای نت های توبروز، یاسمین و رانگون کریپر است. این یک رایحه مدرن و رمانتیک است.",
    category: "عطرها",
    price: 79.99,
    discountPercentage: 14.39,
    rating: 2.74,
    stock: 91,
    tags: ["عطرها", "عطر"],
    brand: "Gucci",
    sku: "FRA-GUC-GUC-010",
    weight: 7,
    dimensions: {
      width: 20.92,
      height: 21.68,
      depth: 11.2,
    },
    warrantyInformation: "گارانتی 6 ماهه",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 1,
        comment: "خیلی ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "خیلی از خریدم راضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "3170832177880",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
  },
  {
    id: 11,
    title: "تخت آنیبال کلمبو",
    description:
      "تخت آنیبال کلمبو یک قاب تخت لوکس و ظریف است که با مواد با کیفیت بالا برای یک اتاق خواب راحت و شیک ساخته شده است.",
    category: "مبلمان",
    price: 1899.99,
    discountPercentage: 8.57,
    rating: 4.77,
    stock: 88,
    tags: ["مبلمان", "تخت"],
    brand: "Annibale Colombo",
    sku: "FUR-ANN-ANN-011",
    weight: 10,
    dimensions: {
      width: 28.16,
      height: 25.36,
      depth: 17.28,
    },
    warrantyInformation: "گارانتی 1 ساله",
    shippingInformation: "ارسال در 1 ماه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 2,
        comment: "توصیه نمی کنم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Christopher West",
        reviewerEmail: "christopher.west@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Vivian Carter",
        reviewerEmail: "vivian.carter@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mason Wright",
        reviewerEmail: "mason.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "3610757456581",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp",
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp",
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
  },
  {
    id: 12,
    title: "مبلمان آنیبال کلمبو",
    description:
      "مبلمان آنیبال کلمبو یک گزینه نشیمن پیچیده و راحت است که دارای طراحی ظریف و روکش با کیفیت بالا برای اتاق نشیمن شما می باشد.",
    category: "مبلمان",
    price: 2499.99,
    discountPercentage: 14.4,
    rating: 3.92,
    stock: 60,
    tags: ["مبلمان", "مبلمان"],
    brand: "Annibale Colombo",
    sku: "FUR-ANN-ANN-012",
    weight: 6,
    dimensions: {
      width: 12.75,
      height: 20.55,
      depth: 19.06,
    },
    warrantyInformation: "گارانتی مادام العمر",
    shippingInformation: "ارسال در 1 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 3,
        comment: "خیلی از خریدم ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Christian Perez",
        reviewerEmail: "christian.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "ارسال سریع!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lillian Bishop",
        reviewerEmail: "lillian.bishop@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lillian Simmons",
        reviewerEmail: "lillian.simmons@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "1777662847736",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp",
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp",
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
  },
  {
    id: 13,
    title: "میز کنار تخت گیلاس آفریقایی",
    description:
      "میز کنار تخت گیلاس آفریقایی یک افزودنی شیک و کاربردی به اتاق خواب شما است که فضای ذخیره سازی مناسب و لمسی از ظرافت را ارائه می دهد.",
    category: "مبلمان",
    price: 299.99,
    discountPercentage: 19.09,
    rating: 2.87,
    stock: 64,
    tags: ["مبلمان", "میزهای کنار تخت"],
    brand: "Furniture Co.",
    sku: "FUR-FUR-BED-013",
    weight: 2,
    dimensions: {
      width: 13.47,
      height: 24.99,
      depth: 27.35,
    },
    warrantyInformation: "گارانتی 5 ساله",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aaliyah Hanson",
        reviewerEmail: "aaliyah.hanson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "توصیه می شود!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Avery Barnes",
        reviewerEmail: "avery.barnes@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 3,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "6441287925979",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp",
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp",
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
  },
  {
    id: 14,
    title: "صندلی کنفرانس اجرایی نول سارینن",
    description:
      "صندلی کنفرانس اجرایی نول سارینن یک صندلی مدرن و ارگونومیک است که با طراحی بی زمان برای دفتر کار یا اتاق کنفرانس شما عالی است.",
    category: "مبلمان",
    price: 499.99,
    discountPercentage: 2.01,
    rating: 4.88,
    stock: 26,
    tags: ["مبلمان", "صندلی های اداری"],
    brand: "Knoll",
    sku: "FUR-KNO-KNO-014",
    weight: 10,
    dimensions: {
      width: 13.81,
      height: 7.5,
      depth: 5.62,
    },
    warrantyInformation: "گارانتی 2 ساله",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 2,
        comment: "هدر دادن پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ella Cook",
        reviewerEmail: "ella.cook@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "خیلی ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "دوباره می خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elena Long",
        reviewerEmail: "elena.long@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 60 روزه",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "8919386859966",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp",
      "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp",
      "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
  },
  {
    id: 15,
    title: "سینک دستشویی چوبی با آینه",
    description:
      "سینک دستشویی چوبی با آینه یک افزودنی منحصر به فرد و شیک به حمام شما است که دارای یک کانتر توپ چوبی و یک آینه هماهنگ می باشد.",
    category: "مبلمان",
    price: 799.99,
    discountPercentage: 8.8,
    rating: 3.59,
    stock: 7,
    tags: ["مبلمان", "حمام"],
    brand: "Bath Trends",
    sku: "FUR-BAT-WOO-015",
    weight: 10,
    dimensions: {
      width: 7.98,
      height: 8.88,
      depth: 28.46,
    },
    warrantyInformation: "گارانتی 3 ساله",
    shippingInformation: "ارسال در 3-5 روز کاری",
    availabilityStatus: "موجودی کم",
    reviews: [
      {
        rating: 4,
        comment: "ارسال سریع!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Logan Torres",
        reviewerEmail: "logan.torres@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "خیلی خوشحالم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aria Parker",
        reviewerEmail: "aria.parker@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Dylan Wells",
        reviewerEmail: "dylan.wells@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 60 روزه",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "1958104402873",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp",
      "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp",
      "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
  },
  {
    id: 16,
    title: "سیب",
    description:
      "سیب های تازه و ترد، عالی برای میان وعده یا استفاده در دستور العمل های مختلف.",
    category: "خواربار",
    price: 1.99,
    discountPercentage: 12.62,
    rating: 4.19,
    stock: 8,
    tags: ["میوه ها"],
    sku: "GRO-BRD-APP-016",
    weight: 9,
    dimensions: {
      width: 13.66,
      height: 11.01,
      depth: 9.73,
    },
    warrantyInformation: "گارانتی 3 ساله",
    shippingInformation: "ارسال در 2 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "خیلی راضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "خیلی ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Scarlett Bowman",
        reviewerEmail: "scarlett.bowman@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "خیلی از خریدم ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "William Gonzalez",
        reviewerEmail: "william.gonzalez@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 90 روزه",
    minimumOrderQuantity: 7,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "7962803553314",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/product-images/groceries/apple/1.webp"],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
  },
  {
    id: 17,
    title: "استیک گوشت گاو",
    description:
      "استیک گوشت گاو با کیفیت بالا، عالی برای کباب کردن یا پختن به سطح مطلوب شما.",
    category: "خواربار",
    price: 12.99,
    discountPercentage: 9.61,
    rating: 4.47,
    stock: 86,
    tags: ["گوشت"],
    sku: "GRO-BRD-BEE-017",
    weight: 10,
    dimensions: {
      width: 18.9,
      height: 5.77,
      depth: 18.57,
    },
    warrantyInformation: "گارانتی 3 ساله",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 3,
        comment: "توصیه نمی کنم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "ارسال سریع!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Alexander Jones",
        reviewerEmail: "alexander.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "ارزش عالی برای پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Natalie Harris",
        reviewerEmail: "natalie.harris@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 60 روزه",
    minimumOrderQuantity: 43,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "5640063409695",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
  },
  {
    id: 18,
    title: "غذای گربه",
    description:
      "غذای مغذی گربه که برای تأمین نیازهای غذایی دوست گربه سان شما فرموله شده است.",
    category: "خواربار",
    price: 8.99,
    discountPercentage: 9.58,
    rating: 3.13,
    stock: 46,
    tags: ["لوازم حیوانات خانگی", "غذای گربه"],
    sku: "GRO-BRD-FOO-018",
    weight: 10,
    dimensions: {
      width: 18.08,
      height: 9.26,
      depth: 21.86,
    },
    warrantyInformation: "گارانتی 1 ساله",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 3,
        comment: "توصیه نمی کنم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Noah Lewis",
        reviewerEmail: "noah.lewis@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "خیلی از خریدم ناراضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "خیلی ناامید شدم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ethan Thompson",
        reviewerEmail: "ethan.thompson@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 18,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "1483991328610",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp",
  },
  {
    id: 19,
    title: "گوشت مرغ",
    description: "گوشت مرغ تازه و لطیف، مناسب برای تهیه های مختلف آشپزی.",
    category: "خواربار",
    price: 9.99,
    discountPercentage: 13.7,
    rating: 3.19,
    stock: 97,
    tags: ["گوشت"],
    sku: "GRO-BRD-CHI-019",
    weight: 1,
    dimensions: {
      width: 11.03,
      height: 22.11,
      depth: 16.01,
    },
    warrantyInformation: "گارانتی 1 ساله",
    shippingInformation: "ارسال در 1 ماه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "توصیه می شود!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jackson Evans",
        reviewerEmail: "jackson.evans@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "ارزش قیمت را ندارد!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Sadie Morales",
        reviewerEmail: "sadie.morales@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 22,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "8829514594521",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp",
      "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp",
  },
  {
    id: 20,
    title: "روغن آشپزی",
    description:
      "روغن آشپزی همه کاره مناسب برای سرخ کردن، تفت دادن و کاربردهای مختلف آشپزی.",
    category: "خواربار",
    price: 4.99,
    discountPercentage: 9.33,
    rating: 4.8,
    stock: 10,
    tags: ["ملزومات آشپزی"],
    sku: "GRO-BRD-COO-020",
    weight: 5,
    dimensions: {
      width: 19.95,
      height: 27.54,
      depth: 24.86,
    },
    warrantyInformation: "گارانتی مادام العمر",
    shippingInformation: "ارسال در 1-2 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "خیلی از خریدم راضی هستم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Victoria McDonald",
        reviewerEmail: "victoria.mcdonald@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "توصیه نمی کنم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Hazel Evans",
        reviewerEmail: "hazel.evans@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "دوباره می خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Zoe Bennett",
        reviewerEmail: "zoe.bennett@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 30 روزه",
    minimumOrderQuantity: 46,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "4874727824518",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp",
  },
  {
    id: 21,
    title: "خیار",
    description:
      "خیارهای ترد و آبرسان، ایده آل برای سالاد، میان وعده یا به عنوان یک طرف تازه.",
    category: "خواربار",
    price: 1.49,
    discountPercentage: 0.16,
    rating: 4.07,
    stock: 84,
    tags: ["سبزیجات"],
    sku: "GRO-BRD-CUC-021",
    weight: 4,
    dimensions: {
      width: 12.8,
      height: 28.38,
      depth: 21.34,
    },
    warrantyInformation: "گارانتی 2 ساله",
    shippingInformation: "ارسال در 1-2 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "ارزش عالی برای پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Savannah Gomez",
        reviewerEmail: "savannah.gomez@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "James Davis",
        reviewerEmail: "james.davis@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "5300066378225",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp",
  },
  {
    id: 22,
    title: "غذای سگ",
    description:
      "غذای سگ فرموله شده ویژه طراحی شده برای تأمین مواد مغذی ضروری برای همراه سگ شما.",
    category: "خواربار",
    price: 10.99,
    discountPercentage: 10.27,
    rating: 4.55,
    stock: 71,
    tags: ["لوازم حیوانات خانگی", "غذای سگ"],
    sku: "GRO-BRD-FOO-022",
    weight: 10,
    dimensions: {
      width: 16.93,
      height: 27.15,
      depth: 9.29,
    },
    warrantyInformation: "بدون گارانتی",
    shippingInformation: "ارسال در 1-2 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Edwards",
        reviewerEmail: "nicholas.edwards@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "محصول فوق العاده!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Zachary Lee",
        reviewerEmail: "zachary.lee@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 60 روزه",
    minimumOrderQuantity: 43,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "5906686116469",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp",
  },
  {
    id: 23,
    title: "تخم مرغ",
    description: "تخم مرغ تازه، یک ماده همه کاره برای پخت، پخت و پز یا صبحانه.",
    category: "خواربار",
    price: 2.99,
    discountPercentage: 11.05,
    rating: 2.53,
    stock: 9,
    tags: ["لبنیات"],
    sku: "GRO-BRD-EGG-023",
    weight: 2,
    dimensions: {
      width: 11.42,
      height: 7.44,
      depth: 16.95,
    },
    warrantyInformation: "گارانتی 1 هفته ای",
    shippingInformation: "ارسال در 1 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 3,
        comment: "محصول ناامید کننده!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Penelope King",
        reviewerEmail: "penelope.king@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "کیفیت ضعیف!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "خیلی خوشحالم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 32,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "3478638588469",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp"],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp",
  },
  {
    id: 24,
    title: "استیک ماهی",
    description:
      "استیک ماهی با کیفیت، مناسب برای کباب کردن، پختن یا سرخ کردن در تابه.",
    category: "خواربار",
    price: 14.99,
    discountPercentage: 4.23,
    rating: 3.78,
    stock: 74,
    tags: ["غذای دریایی"],
    sku: "GRO-BRD-FIS-024",
    weight: 6,
    dimensions: {
      width: 14.95,
      height: 26.31,
      depth: 11.27,
    },
    warrantyInformation: "گارانتی 1 ماهه",
    shippingInformation: "ارسال در 3-5 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 2,
        comment: "دوباره نمی خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Caleb Perkins",
        reviewerEmail: "caleb.perkins@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Isabella Jackson",
        reviewerEmail: "isabella.jackson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "ارزش عالی برای پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nathan Dixon",
        reviewerEmail: "nathan.dixon@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 60 روزه",
    minimumOrderQuantity: 50,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9595036192098",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp",
  },
  {
    id: 25,
    title: "فلفل دلمه ای سبز",
    description:
      "فلفل دلمه ای سبز تازه و پرانرژی، عالی برای اضافه کردن رنگ و طعم به غذاهای شما.",
    category: "خواربار",
    price: 1.29,
    discountPercentage: 0.16,
    rating: 3.25,
    stock: 33,
    tags: ["سبزیجات"],
    sku: "GRO-BRD-GRE-025",
    weight: 2,
    dimensions: {
      width: 15.33,
      height: 26.65,
      depth: 14.44,
    },
    warrantyInformation: "گارانتی 1 ماهه",
    shippingInformation: "ارسال در 1 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "توصیه می شود!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Avery Carter",
        reviewerEmail: "avery.carter@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "توصیه نمی کنم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Henry Hill",
        reviewerEmail: "henry.hill@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 30 روزه",
    minimumOrderQuantity: 12,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "2365227493323",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp",
  },
  {
    id: 26,
    title: "فلفل تند سبز",
    description:
      "فلفل تند سبز تند، ایده آل برای اضافه کردن حرارت به دستور العمل های مورد علاقه شما.",
    category: "خواربار",
    price: 0.99,
    discountPercentage: 1,
    rating: 3.66,
    stock: 3,
    tags: ["سبزیجات"],
    sku: "GRO-BRD-GRE-026",
    weight: 7,
    dimensions: {
      width: 15.38,
      height: 18.12,
      depth: 19.92,
    },
    warrantyInformation: "گارانتی 2 ساله",
    shippingInformation: "ارسال در 1 هفته",
    availabilityStatus: "موجودی کم",
    reviews: [
      {
        rating: 4,
        comment: "محصول عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "هدر دادن پول!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Noah Lewis",
        reviewerEmail: "noah.lewis@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "خیلی ناامید شدم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 30 روزه",
    minimumOrderQuantity: 39,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9335000538563",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp",
  },
  {
    id: 27,
    title: "شیشه عسل",
    description:
      "عسل خالص و طبیعی در یک شیشه مناسب، عالی برای شیرین کردن نوشیدنی ها یا چکیدن روی غذا.",
    category: "خواربار",
    price: 6.99,
    discountPercentage: 14.4,
    rating: 3.97,
    stock: 34,
    tags: ["چاشنی ها"],
    sku: "GRO-BRD-HON-027",
    weight: 2,
    dimensions: {
      width: 9.28,
      height: 21.72,
      depth: 17.74,
    },
    warrantyInformation: "گارانتی 1 ماهه",
    shippingInformation: "ارسال در 1-2 روز کاری",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 1,
        comment: "خیلی ناامید شدم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Autumn Gomez",
        reviewerEmail: "autumn.gomez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Benjamin Wilson",
        reviewerEmail: "benjamin.wilson@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "خیلی ناامید شدم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Edwards",
        reviewerEmail: "nicholas.edwards@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 90 روزه",
    minimumOrderQuantity: 47,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "6354306346329",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
  },
  {
    id: 28,
    title: "بستنی",
    description:
      "بستنی خامه ای و خوشمزه، در طعم های مختلف برای یک خوراکی لذت بخش موجود است.",
    category: "خواربار",
    price: 5.49,
    discountPercentage: 8.69,
    rating: 3.39,
    stock: 27,
    tags: ["دسرها"],
    sku: "GRO-BRD-CRE-028",
    weight: 1,
    dimensions: {
      width: 14.83,
      height: 15.07,
      depth: 24.2,
    },
    warrantyInformation: "گارانتی 1 ماهه",
    shippingInformation: "ارسال در 2 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "خیلی خوشحالم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elijah Cruz",
        reviewerEmail: "elijah.cruz@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jace Smith",
        reviewerEmail: "jace.smith@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "بسیار تحت تأثیر قرار گرفتم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Sadie Morales",
        reviewerEmail: "sadie.morales@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 42,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "0788954559076",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp",
      "https://cdn.dummyjson.com/product-images/groceries/ice-cream/2.webp",
      "https://cdn.dummyjson.com/product-images/groceries/ice-cream/3.webp",
      "https://cdn.dummyjson.com/product-images/groceries/ice-cream/4.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp",
  },
  {
    id: 29,
    title: "آبمیوه",
    description:
      "آبمیوه میوه ای تازه، پر از ویتامین و عالی برای هیدراته ماندن.",
    category: "خواربار",
    price: 3.99,
    discountPercentage: 12.06,
    rating: 3.94,
    stock: 50,
    tags: ["نوشیدنی ها"],
    sku: "GRO-BRD-JUI-029",
    weight: 1,
    dimensions: {
      width: 18.56,
      height: 21.46,
      depth: 28.02,
    },
    warrantyInformation: "گارانتی 6 ماهه",
    shippingInformation: "ارسال در 1 هفته",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 5,
        comment: "کیفیت عالی!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "دوباره می خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Bella Grant",
        reviewerEmail: "bella.grant@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "محصول فوق العاده!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aria Flores",
        reviewerEmail: "aria.flores@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت وجود ندارد",
    minimumOrderQuantity: 25,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "6936112580956",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/product-images/groceries/juice/1.webp"],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp",
  },
  {
    id: 30,
    title: "کیوی",
    description:
      "کیوی غنی از مواد مغذی، عالی برای میان وعده یا اضافه کردن یک پیچ و تاب استوایی به غذاهای شما.",
    category: "خواربار",
    price: 2.49,
    discountPercentage: 15.22,
    rating: 4.93,
    stock: 99,
    tags: ["میوه ها"],
    sku: "GRO-BRD-KIW-030",
    weight: 5,
    dimensions: {
      width: 19.4,
      height: 18.67,
      depth: 17.13,
    },
    warrantyInformation: "گارانتی 6 ماهه",
    shippingInformation: "ارسال شبانه",
    availabilityStatus: "موجود در انبار",
    reviews: [
      {
        rating: 4,
        comment: "توصیه می شود!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Emily Brown",
        reviewerEmail: "emily.brown@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "دوباره نمی خرم!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jackson Morales",
        reviewerEmail: "jackson.morales@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "ارسال سریع!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "سیاست بازگشت 7 روزه",
    minimumOrderQuantity: 30,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "2530169917252",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp"],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp",
  },
];
export const fakestoreData: FakeProduct[] = [
  {
    id: 1,
    title: "کوله پشتی فجل ریون - فولدسک شماره 1، مناسب برای 15 لپ تاپ",
    price: 109.95,
    description:
      "کیف کامل شما برای استفاده روزمره و پیاده روی در جنگل. لپ تاپ خود را (تا 15 اینچ) در آستین بالشتکی قرار دهید، برای استفاده روزمره",
    category: "لباس مردانه",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
    rating: {
      rate: 3.9,
      count: 120,
    },
  },
  {
    id: 2,
    title: "تیشرت مردانه معمولی پریمیوم با fit باریک",
    price: 22.3,
    description:
      "سبک fit باریک، آستین راگلان کنتراست، پلاکت هنلی سه دکمه، پارچه سبک و نرم برای پوشیدن قابل تنفس و راحت. و پیراهن های دوخته شده محکم با یقه گرد برای دوام و fit عالی برای پوشیدن مد معمولی و طرفداران پر و پا قرص بیسبال ساخته شده است. یقه گرد سبک هنلی شامل یک پلاکت سه دکمه است.",
    category: "لباس مردانه",
    image:
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png",
    rating: {
      rate: 4.1,
      count: 259,
    },
  },
  {
    id: 3,
    title: "ژاکت پنبه ای مردانه",
    price: 55.99,
    description:
      "ژاکت های عالی برای بهار/پاییز/زمستان، مناسب برای بسیاری از مناسبت ها، مانند کار، پیاده روی، کمپینگ، کوهنوردی/صخره نوردی، دوچرخه سواری، مسافرت یا فضای باز دیگر. انتخاب هدیه خوب برای شما یا عضو خانواده تان. هدیه ای پر از عشق برای پدر، شوهر یا پسر در این روز شکرگزاری یا کریسمس.",
    category: "لباس مردانه",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
    rating: {
      rate: 4.7,
      count: 500,
    },
  },
  {
    id: 4,
    title: "لباس مردانه معمولی با fit باریک",
    price: 15.99,
    description:
      "رنگ ممکن است بین صفحه نمایش و عمل کمی متفاوت باشد. / لطفاً توجه داشته باشید که ساختار بدن بر اساس فرد متفاوت است، بنابراین، اطلاعات دقیق اندازه باید در زیر در توضیحات محصول مرور شود.",
    category: "لباس مردانه",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png",
    rating: {
      rate: 2.1,
      count: 430,
    },
  },
  {
    id: 5,
    title:
      "دستبند زنجیر ایستگاهی اژدهای ناگا طلا و نقره جان هاردی زنانه افسانه ها",
    price: 695,
    description:
      "از مجموعه افسانه های ما، ناگا از اژدهای افسانه ای آب که از مروارید اقیانوس محافظت می کند الهام گرفته شده است. برای بهره مندی از عشق و فراوانی به سمت داخل بپوشید، یا برای محافظت به سمت خارج.",
    category: "جواهرات",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png",
    rating: {
      rate: 4.6,
      count: 400,
    },
  },
  {
    id: 6,
    title: "میکروپیو پتی طلای خالص",
    price: 168,
    description:
      "رضایت تضمین شده. هر سفارش را در عرض 30 روز مرجوع یا تعویض کنید. طراحی و فروخته شده توسط مرکز حفیظ در ایالات متحده. رضایت تضمین شده. هر سفارش را در عرض 30 روز مرجوع یا تعویض کنید.",
    category: "جواهرات",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png",
    rating: {
      rate: 3.9,
      count: 70,
    },
  },
  {
    id: 7,
    title: "شاهزاده خانم روکش طلای سفید",
    price: 9.99,
    description:
      "حلقه وعده الماس سولیتیر نامزدی عروسی کلاسیک برای او. هدایا برای لذت بردن بیشتر از عشق تان برای نامزدی، عروسی، سالگرد، روز ولنتاین...",
    category: "جواهرات",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png",
    rating: {
      rate: 3,
      count: 400,
    },
  },
  {
    id: 8,
    title: "جغد سوراخ شده دبل فولاد ضد زنگ روکش طلای رز",
    price: 10.99,
    description:
      "گوشواره های پلاگ تونل دبل فلیر روکش طلای رز. ساخته شده از فولاد ضد زنگ 316L",
    category: "جواهرات",
    image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png",
    rating: {
      rate: 1.9,
      count: 100,
    },
  },
  {
    id: 9,
    title: "درایو اکسترنال پرتابل وسترن دیجیتال المنت 2 ترابایت - USB 3.0",
    price: 64,
    description:
      "سازگاری با USB 3.0 و USB 2.0 انتقال سریع داده ها بهبود عملکرد کامپیوتر ظرفیت بالا؛ قالب بندی شده NTFS برای ویندوز 10، ویندوز 8.1، ویندوز 7؛ ممکن است قالب بندی مجدد برای سیستم عامل های دیگر مورد نیاز باشد؛ سازگاری ممکن است بسته به پیکربندی سخت افزار و سیستم عامل کاربر متفاوت باشد",
    category: "الکترونیک",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
    rating: {
      rate: 3.3,
      count: 203,
    },
  },
  {
    id: 10,
    title:
      "اس اس دی داخلی ساندیسک اس اس دی پلاس 1 ترابایت - SATA III 6 گیگابیت بر ثانیه",
    price: 109,
    description:
      "ارتقای آسان برای بوت آپ، شات داون، لود و پاسخ برنامه سریعتر (در مقایسه با هارد درایو SATA 2.5 اینچی 5400 دور در دقیقه؛ بر اساس مشخصات منتشر شده و تست های بنچمارک داخلی با استفاده از امتیازات PCMark vantage) عملکرد نوشتن انفجاری را تقویت می کند، آن را برای بارهای کاری معمولی کامپیوتر ایده آل می کند تعادل کامل عملکرد و قابلیت اطمینان سرعت خواندن/نوشتن تا 535 مگابایت بر ثانیه/450 مگابایت بر ثانیه (بر اساس تست داخلی؛ عملکرد ممکن است بسته به ظرفیت درایو، دستگاه میزبان، سیستم عامل و برنامه متفاوت باشد.)",
    category: "الکترونیک",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png",
    rating: {
      rate: 2.9,
      count: 470,
    },
  },
  {
    id: 11,
    title:
      "اس اس دی سلیکون پاور 256 گیگابایت سه بعدی ناند A55 اس ال سی کش تقویت عملکرد SATA III 2.5",
    price: 109,
    description:
      "فلش سه بعدی ناند برای ارائه سرعت انتقال بالا اعمال می شود سرعت انتقال قابل توجه که بوت آپ سریعتر و بهبود عملکرد کلی سیستم را امکان پذیر می کند. فناوری کش اس ال سی پیشرفته اجازه تقویت عملکرد و طول عمر بیشتر را می دهد طراحی باریک 7 میلی متری مناسب برای اولترابوک ها و نوت بوک های اولترا اسلیم. از دستور TRIM، فناوری جمع آوری زباله، RAID و ECC (بررسی و تصحیح خطا) برای ارائه عملکرد بهینه و قابلیت اطمینان增强 پشتیبانی می کند.",
    category: "الکترونیک",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png",
    rating: {
      rate: 4.8,
      count: 319,
    },
  },
  {
    id: 12,
    title:
      "درایو گیمینگ وسترن دیجیتال 4 ترابایت کار می کند با پلی استیشن 4 درایو اکسترنال پرتابل",
    price: 114,
    description:
      "تجربه گیمینگ PS4 خود را گسترش دهید، در هر جایی بازی کنید سریع و آسان، راه اندازی طراحی شیک با ظرفیت بالا، گارانتی محدود سازنده 3 ساله",
    category: "الکترونیک",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
    rating: {
      rate: 4.8,
      count: 400,
    },
  },
  {
    id: 13,
    title:
      "ایسر SB220Q bi 21.5 اینچ فول اچ دی (1920 در 1080) آی پی اس اولترا نازک",
    price: 599,
    description:
      "صفحه نمایش 21.5 اینچی فول اچ دی (1920 در 1080) وایدسکرین آی پی اس و فناوری ریدئون فری سینک. بدون سازگاری برای نصب VESA نرخ تازه سازی: 75 هرتز - استفاده از پورت اچ دی ام آی طراحی بدون فریم | اولترا نازک | زمان پاسخ 4 میلی ثانیه | پنل آی پی اس نسبت تصویر - 16:9. رنگ های پشتیبانی شده - 16.7 میلیون رنگ. روشنایی - 250 نیت زاویه کج -5 درجه تا 15 درجه. زاویه دید افقی-178 درجه. زاویه دید عمودی-178 درجه 75 هرتز",
    category: "الکترونیک",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
    rating: {
      rate: 2.9,
      count: 250,
    },
  },
  {
    id: 14,
    title:
      "مانیتور گیمینگ خمیده 144 هرتز سامسونگ 49 اینچ (LC49HG90DMNXZA) – سوپر اولترا واید اسکرین کی لید",
    price: 999.99,
    description:
      "مانیتور گیمینگ خمیده 49 اینچی سوپر اولترا واید 32:9 با دو صفحه 27 اینچی کنار هم فناوری کوانتوم دات (کی لید)، پشتیبانی اچ دی آر و کالیبراسیون کارخانه رنگ و کنتراست فوق العاده واقعی و دقیق را ارائه می دهد نرخ تازه سازی بالا 144 هرتز و زمان پاسخ فوق سریع 1 میلی ثانیه برای حذف محو شدگی حرکت، سایه و کاهش تاخیر ورودی کار می کنند",
    category: "الکترونیک",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
    rating: {
      rate: 2.2,
      count: 140,
    },
  },
  {
    id: 15,
    title: "ژاکت اسنوبورد 3 در 1 زنانه بییلاسلزن کت های زمستانی",
    price: 56.99,
    description:
      "توجه: ژاکت ها سایز استاندارد آمریکایی هستند، لطفاً سایز را مانند پوشش معمولی خود انتخاب کنید جنس: 100% پلی استر؛ جنس آستر قابل جدا شدن: فلز گرم. آستر کاربردی قابل جدا شدن: سازگار با پوست، سبک وزن و گرم. ژاکت آستر یقه ایستاده، شما را در هوای سرد گرم نگه می دارد. جیب های زیپ دار: 2 جیب دستی زیپ دار، 2 جیب زیپ دار روی سینه (به اندازه کافی برای نگهداری کارت یا کلید) و 1 جیب مخفی داخل. جیب های دستی زیپ دار و جیب مخفی وسایل شما را ایمن نگه می دارند. طراحی انسان محور: هود قابل تنظیم و قابل جدا شدن و مچ قابل تنظیم برای جلوگیری از باد و آب، برای fit راحت. طراحی قابل جدا شدن 3 در 1 راحتی بیشتری فراهم می کند، می توانید کت و آستر داخلی را در صورت نیاز جدا کنید، یا با هم بپوشید. برای فصل های مختلف مناسب است و به شما کمک می کند تا با آب و هوای مختلف سازگار شوید",
    category: "لباس زنانه",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png",
    rating: {
      rate: 2.6,
      count: 235,
    },
  },
  {
    id: 16,
    title:
      "ژاکت موتورسوار بایکر زنانه هوددار قابل جدا شدن لاک و لاو چرم مصنوعی",
    price: 29.95,
    description:
      "100% پلی اورتان (پوسته) 100% پلی استر (آستر) 75% پلی استر 25% پنبه (سویشرت)، جنس چرم مصنوعی برای استایل و راحتی / 2 جیب جلو، ژاکت جین استایل چرم مصنوعی هوددار 2 به 1، دکمه روی کمر / دوخت جزئی در کناره ها، فقط شستشوی دستی / وایتکس نکنید / خشک کردن روی بند / اتو نکنید",
    category: "لباس زنانه",
    image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png",
    rating: {
      rate: 2.9,
      count: 340,
    },
  },
  {
    id: 17,
    title: "کت بارانی زنانه ویندبریکر راه راه بارانی کوهنوردی",
    price: 39.99,
    description:
      "سبک وزن عالی برای سفر یا پوشیدن معمولی---آستین بلند با هود، طراحی کمر قابل تنظیم با بند کشی. کت بارانی با بسته شدن جلو دکمه و زیپ، کاملاً راه راه آستر دار و کت بارانی دارای 2 جیب کناری با اندازه خوب برای نگهداری انواع چیزها، باسن را می پوشاند، و هود سخاوتمندانه است اما زیاده روی نمی کند. هود آستر پنبه ای چسبیده با بندهای کشی قابل تنظیم ظاهری واقعاً استایلی به آن می دهد.",
    category: "لباس زنانه",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png",
    rating: {
      rate: 3.8,
      count: 679,
    },
  },
  {
    id: 18,
    title: "تیشرت زنانه ام بی جی آستین کوتاه ساده یقه قایقی V",
    price: 9.85,
    description:
      "95% ریون 5% اسپاندکس، ساخته شده در آمریکا یا وارداتی، وایتکس نکنید، پارچه سبک وزن با کشش عالی برای راحتی، دنده دار روی آستین ها و یقه / دوخت دوتایی روی لبه پایین",
    category: "لباس زنانه",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png",
    rating: {
      rate: 4.7,
      count: 130,
    },
  },
  {
    id: 19,
    title: "تیشرت زنانه اپنا آستین کوتاه رطوبت",
    price: 7.95,
    description:
      "100% پلی استر، قابل شستشو با ماشین، 100% پلی استر کاتیونی اینترلاک، شستشو با ماشین و از قبل جمع شده برای fit عالی، سبک وزن، گشاد و بسیار قابل تنفس با پارچه جاذب رطوبت که به دور نگه داشتن رطوبت کمک می کند، پارچه نرم سبک وزن با یقه V راحت و fit باریک تر، silhouette ای ظریف و زنانه تر و راحتی اضافی ارائه می دهد",
    category: "لباس زنانه",
    image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png",
    rating: {
      rate: 4.5,
      count: 146,
    },
  },
  {
    id: 20,
    title: "تیشرت زنانه دنووی معمولی پنبه ای آستین کوتاه",
    price: 12.99,
    description:
      "95% پنبه، 5% اسپاندکس، ویژگی ها: معمولی، آستین کوتاه، چاپ حروف، یقه V، تی شرت های مد، پارچه نرم است و مقداری کش دارد.، مناسبت: معمولی/اداری/ساحل/مدرسه/خانه/خیابان. فصل: بهار، تابستان، پاییز، زمستان.",
    category: "لباس زنانه",
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png",
    rating: {
      rate: 3.6,
      count: 145,
    },
  },
];
